name: run
run_id: commands[0]
env HOME: /home/manuel
env LANG: en_US.UTF-8
env TERM: xterm-256color
env LD_LIBRARY_PATH: /opt/xilinx/xrt/lib:
env PATH: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/.tox/test_app/bin:/home/manuel/.nvm/versions/node/v14.4.0/bin:/home/manuel/anaconda3/envs/test_api_credit/bin:/home/manuel/anaconda3/condabin:/opt/xilinx/xrt/bin:/tools/Xilinx/Vitis_HLS/2021.2/bin:/tools/Xilinx/Model_Composer/2021.2/bin:/tools/Xilinx/Vitis/2021.2/bin:/tools/Xilinx/Vitis/2021.2/gnu/microblaze/lin/bin:/tools/Xilinx/Vitis/2021.2/gnu/arm/lin/bin:/tools/Xilinx/Vitis/2021.2/gnu/microblaze/linux_toolchain/lin64_le/bin:/tools/Xilinx/Vitis/2021.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin:/tools/Xilinx/Vitis/2021.2/gnu/aarch32/lin/gcc-arm-none-eabi/bin:/tools/Xilinx/Vitis/2021.2/gnu/aarch64/lin/aarch64-linux/bin:/tools/Xilinx/Vitis/2021.2/gnu/aarch64/lin/aarch64-none/bin:/tools/Xilinx/Vitis/2021.2/gnu/armr5/lin/gcc-arm-none-eabi/bin:/tools/Xilinx/Vitis/2021.2/tps/lnx64/cmake-3.3.2/bin:/tools/Xilinx/Vitis/2021.2/aietools/bin:/tools/Xilinx/Vivado/2021.2/bin:/tools/Xilinx/DocNav:/home/manuel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/cuda/bin
env PYTHONHASHSEED: 289721231
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/.tox
env TOX_ENV_DIR: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/.tox/test_app
env VIRTUAL_ENV: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/.tox/test_app
env COLUMNS: 190
env LINES: 50
metadata pid: 90235
cwd: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api
allow: /mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: 1

standard error:
Traceback (most recent call last):
  File "/mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/app/main.py", line 8, in <module>
    from app.api import api_router
  File "/mnt/storage/Bowpi/Data Science/cc_approval/rest_api/rest_api/app/api.py", line 33, in <module>
    @api_router.post("/predict", response_model=schemas.PredictionResults, status_code=200)
AttributeError: module 'app.schemas' has no attribute 'PredictionResults'
